inherit_gem:
  rubocop-discourse: stree-compat.yml

# Still work to do in ensuring we don't link old files
Discourse/NoAddReferenceOrAliasesActiveRecordMigration:
  Enabled: false

Discourse/NoResetColumnInformationInMigrations:
  Enabled: true

Lint/Debugger:
  Exclude:
    - script/**/*

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for
    - while
    - if
    - as
    - after
    - in
